name: build
on:
  push:
    branches:
      - master
jobs:
  build-linux:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@master
        with:
          submodules: recursive
      - name: Install dependencies
        run: |
          sudo add-apt-repository universe
          sudo apt-get update -qq
          sudo apt-get install -y clang build-essential libgtk-3-dev libsdl2-dev git ninja-build qt6-base-dev
          sudo apt-get install -y vulkan-tools libvulkan1 libvulkan-dev vulkan-utility-libraries-dev spirv-tools
      - name: Build Kaizen
        run: |
          cmake -G Ninja -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build --config Release
      - name: Collect artifacts
        run: |
          mkdir upload
          cp -r build/src/frontend/{kaizen-qt,resources} upload
      - name: Upload artifacts
        uses: actions/upload-artifact@master
        with:
          name: kaizen-linux
          path: upload
          if-no-files-found: error