name: build
on:
  push:
    branches:
      - master
jobs:
  build-linux:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@master
        with:
          submodules: recursive
      - name: Install dependencies
        run: |
          sudo add-apt-repository universe
          sudo apt-get update -qq
          sudo apt-get install -y clang build-essential libgtk-3-dev git ninja-build qt6-base-dev
          sudo apt-get install -y vulkan-tools libvulkan1 libvulkan-dev vulkan-utility-libraries-dev spirv-tools
      - name: Build Kaizen
        run: |
          cmake -G Ninja -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build --config Release
      - name: Collect artifacts
        run: |
          mkdir upload
          cp -r build/src/frontend/{kaizen-qt,resources} upload
      - name: Upload artifacts
        uses: actions/upload-artifact@master
        with:
          name: kaizen-linux
          path: upload
          if-no-files-found: error
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@master
        with:
          submodules: recursive
      - name: Setup Qt
        uses: jurplel/install-qt-action@v3
        with:
          arch: win64_msvc2019_64
          version: 6.6.*
      - name: Build Kaizen
        run: |
          cmake -B build -T clangcl -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_BUILD_TYPE=Release
          cmake --build build --config Release
      - name: Collect artifacts
        run: |
          mkdir upload
          cp build/src/frontend/Release/kaizen-qt.exe upload
          mkdir upload/resources
          cp resources/* upload/resources
          windeployqt --dir upload upload/kaizen-qt.exe
      - name: Upload artifacts
        uses: actions/upload-artifact@master
        with:
          name: kaizen-windows
          path: upload
          if-no-files-found: error